CREATE UNLOGGED TABLE IF NOT EXISTS raw.d2totals (
    id integer primary key,
    committeeid integer,
    fileddocid integer,
    begfundsavail double precision,
    indivcontribi double precision,
    indivcontribni double precision,
    xferini double precision,
    xferinni double precision,
    loanrvci double precision,
    loanrcvni double precision,
    otherrcti double precision,
    otherrctni double precision,
    totalreceipts double precision,
    inkindi double precision,
    inkindni double precision,
    totalinkind double precision,
    xferouti double precision,
    xferoutni double precision,
    loanmadei double precision,
    loanmadeni double precision,
    expendi double precision,
    expendni double precision,
    independentexpi double precision,
    independentexpni double precision,
    totalexpend double precision,
    debtsi double precision,
    debtsni double precision,
    totaldebts double precision,
    totalinvest double precision,
    endfundsavail double precision,
    archived boolean
);
