CREATE UNLOGGED TABLE IF NOT EXISTS raw.expenditures (
    id integer primary key,
    committeeid integer,
    fileddocid integer,
    etransid character varying,
    lastonlyname character varying,
    firstname character varying,
    expendeddate timestamp without time zone,
    amount double precision,
    aggregateamount double precision,
    address1 character varying,
    address2 character varying,
    city character varying,
    state character varying,
    zip character varying,
    d2part character varying,
    purpose character varying,
    candidatename character varying,
    office character varying,
    supporting boolean,
    opposing boolean,
    archived boolean,
    country character varying,
    redactionrequested boolean
);
