CREATE UNLOGGED TABLE IF NOT EXISTS raw.fileddocs (
    id integer primary key,
    committeeid integer,
    fileddoctype character varying(10),
    docname character varying(30),
    amend boolean,
    comment character varying(100),
    pages integer,
    electiontype character varying,
    electionyear integer,
    rptpdbegdate timestamp without time zone,
    rptpdenddate timestamp without time zone,
    rcvdat character varying,
    rcvddatetime timestamp without time zone,
    source character varying,
    provider character varying,
    signerlastonlyname character varying,
    signerfirstname character varying,
    sbmttrlastonlyname character varying,
    sbmttrfirstname character varying,
    sbmttraddress1 character varying,
    sbmttraddress2 character varying,
    sbmttrcity character varying,
    sbmttrstate character varying,
    sbmttrzip character varying,
    b9signerlastonlyname character varying,
    b9signerfirstname character varying,
    archived boolean,
    clarification text,
    redactionrequested boolean
);
