CREATE UNLOGGED TABLE IF NOT EXISTS raw.Receipts (
    id integer primary key,
    committeeid integer,
    fileddocid integer,
    etransid character varying,
    lastonlyname character varying,
    firstname character varying,
    rcvdate timestamp without time zone,
    amount double precision,
    aggregateamount double precision,
    loanamount double precision,
    occupation character varying,
    employer character varying,
    address1 character varying,
    address2 character varying,
    city character varying,
    state character varying,
    zip character varying,
    d2part character varying,
    description text,
    vendorlastonlyname character varying,
    vendorfirstname character varying,
    vendoraddress1 character varying,
    vendoraddress2 character varying,
    vendorcity character varying,
    vendorstate character varying,
    vendorzip character varying,
    archived boolean,
    country character varying,
    redactionrequested boolean
);
